apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: demo-prodlik-permittering
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://arbeidsgiver.ansatt.dev.nav.no/permittering
  liveness:
    path: /permittering/internal/isAlive
    initialDelay: 20
  readiness:
    path: /permittering/internal/isAlive
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  accessPolicy:
    outbound:
      external:
        - host: pam-ontologi.intern.dev.nav.no
  env:
    - name: GIT_COMMIT
      value: {{commit}}
    - name: MILJO
      value: demo
    - name: BACKEND_BASEURL
      value: http://permitteringsskjema-api
    - name: BACKEND_API_PATH
      value: /permitteringsskjema-api
