apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permittering
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://permitteringsskjema.intern.dev.nav.no/permittering
  liveness:
    path: /permittering/internal/isAlive
  readiness:
    path: /permittering/internal/isAlive
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  idporten:
    sidecar:
      enabled: true
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: permitteringsskjema-api
        - application: pam-ontologi
          namespace: teampam
  envFrom:
    - secret: permittering-secrets
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: GIT_COMMIT
      value: {{commit}}
    - name: MILJO
      value: dev
    - name: LOGIN_URL
      value: https://permitteringsskjema.intern.dev.nav.no/permittering/oauth2/login?redirect=/permittering
    - name: API_AUDIENCE
      value: dev-gcp:permittering-og-nedbemanning:permitteringsskjema-api
    - name: BACKEND_BASEURL
      value: http://permitteringsskjema-api
    - name: BACKEND_API_PATH
      value: /permitteringsskjema-api
    - name: LOGINSERVICE_LOGOUT_URL
      value: https://loginservice.dev.nav.no/slo
