apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permittering
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://permitteringsskjema.dev.nav.no/permittering
  liveness:
    path: /permittering/internal/isAlive
    initialDelay: 20
  readiness:
    path: /permittering/internal/isAlive
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  idporten:
    sidecar:
      enabled: true
    enabled: true
    clientUri: https://permitteringsskjema.dev.nav.no/permittering
    postLogoutRedirectURIs:
      - https://permitteringsskjema.dev.nav.no/permittering/logout-callback
  accessPolicy:
    outbound:
      rules:
        - application: permitteringsskjema-api
        - application: pam-janzz
          namespace: teampam
      external:
        - host: dekoratoren.dev.nav.no
  envFrom:
    - secret: permittering-secrets
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://loginservice.dev.nav.no/login?redirect=https://permitteringsskjema.dev.nav.no/permittering
    - name: API_AUDIENCE
      value: dev-gcp:permittering-og-nedbemanning:permitteringsskjema-api
    - name: BACKEND_BASEURL
      value: http://permitteringsskjema-api
    - name: BACKEND_API_PATH
      value: /permitteringsskjema-api
    - name: LOGINSERVICE_LOGOUT_URL
      value: https://loginservice.dev.nav.no/slo
