name: Build and deploy

on: [push]

jobs:
  compile-test-and-build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
          cache: 'npm'
      - run: npm ci
      - working-directory: ./src/server
        run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: fager
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-to-dev-gcp:
    permissions:
      contents: "read"
      id-token: "write"
    name: Deploy to dev-gcp
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bytt_til_esbuild'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: fager
      - uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ${{ steps.login.outputs.registry }}/permittering:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}

  deploy-to-labs-gcp:
    name: Deploy to labs-gcp
    if: github.ref == 'refs/heads/master'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: fager
      - uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ${{ steps.login.outputs.registry }}/permittering:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: labs-gcp
          RESOURCE: nais/labs-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/master'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: fager
      - uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ${{ steps.login.outputs.registry }}/permittering:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-gcp.yaml
          PRINT_PAYLOAD: true
          VAR: commit=${{ github.sha }}
